apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-next-app
  labels:
    app: my-next-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-next-app
  template:
    metadata:
      labels:
        app: my-next-app
    spec:
      containers:
      - name: my-next-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
