apiVersion: v1
kind: Service
metadata:
  name: my-next-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: my-next-app
