replicaCount: 1

image:
  repository: "058264105592.dkr.ecr.eu-north-1.amazonaws.com/next.js_application"   # Update with your ECR registry
  tag: "latest"                       # Update with the appropriate tag
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
