replicaCount: 1

image:
  repository: "058264105592.dkr.ecr.eu-north-1.amazonaws.com/next.js_application"
  tag: "latest" 
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
