name: Deploy Next.js App to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      id: ecr-login
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-north-1
      run: aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 058264105592.dkr.ecr.eu-north-1.amazonaws.com


    - name: Build Docker image
      run: |
        docker build -t $ECR_REGISTRY:latest .
        docker tag $ECR_REGISTRY:latest $ECR_REGISTRY:latest

    - name: Push Docker image to ECR
      run: |
        docker push $ECR_REGISTRY:latest

    - name: Configure kubectl
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup kubectl
      run: |
        aws eks update-kubeconfig --name my-eks-cluster --region ${{ secrets.AWS_REGION }}

    - name: Deploy with Helm
      run: |
        helm upgrade --install my-next-app helm/my-next-app \
          --set image.repository=${{ steps.login-ecr.outputs.registry }}/my-next-app \
          --set image.tag=latest

    - name: Clean up
      run: |
        docker rmi $ECR_REPOSITORY:$latest || true
